In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
loan = pd.read_csv('kiva_loans_standardized.csv')

In [3]:
# sns.heatmap(loan.corr())
loan.columns

Index(['loan_amount', 'activity_Adult Care', 'activity_Agriculture',
       'activity_Air Conditioning', 'activity_Animal Sales',
       'activity_Aquaculture', 'activity_Arts', 'activity_Auto Repair',
       'activity_Bakery', 'activity_Balut-Making',
       ...
       'country_code_ZM', 'country_code_ZW', 'term_in_months', 'lender_count',
       'repayment_interval_bullet', 'repayment_interval_irregular',
       'repayment_interval_monthly', 'repayment_interval_weekly', 'count_male',
       'count_female'],
      dtype='object', length=274)

In [4]:
import sklearn

In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix

# Model Fitting

## On Logistic Regression

### On Bullet

In [11]:
y = loan['repayment_interval_bullet']


# 'repayment_interval_bullet', 'repayment_interval_irregular', 'repayment_interval_monthly', 'repayment_interval_weekly'
X = loan
del X['repayment_interval_bullet']
del X['repayment_interval_irregular']
del X['repayment_interval_monthly']
del X['repayment_interval_weekly']

In [12]:
X.columns

Index(['loan_amount', 'activity_Adult Care', 'activity_Agriculture',
       'activity_Air Conditioning', 'activity_Animal Sales',
       'activity_Aquaculture', 'activity_Arts', 'activity_Auto Repair',
       'activity_Bakery', 'activity_Balut-Making',
       ...
       'country_code_WS', 'country_code_XK', 'country_code_YE',
       'country_code_ZA', 'country_code_ZM', 'country_code_ZW',
       'term_in_months', 'lender_count', 'count_male', 'count_female'],
      dtype='object', length=270)

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=1)

In [20]:
print(len(X_train),len(X_test),len(y_train),len(y_test))

637644 33561 637644 33561


In [21]:
logmodel = LogisticRegression()

In [22]:
logmodel.fit(X_train,y_train)

c:\program files\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [23]:
predictions = logmodel.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       0.97      0.98      0.97     30096
           1       0.78      0.70      0.73      3465

   micro avg       0.95      0.95      0.95     33561
   macro avg       0.87      0.84      0.85     33561
weighted avg       0.95      0.95      0.95     33561

[[29410   686]
 [ 1056  2409]]


### On Monthly

In [31]:
y = loan['repayment_interval_monthly']

# 'repayment_interval_bullet', 'repayment_interval_irregular', 'repayment_interval_monthly', 'repayment_interval_weekly'
X = loan
del X['repayment_interval_bullet']
del X['repayment_interval_irregular']
del X['repayment_interval_monthly']
del X['repayment_interval_weekly']

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=1)

In [33]:
print(len(X_train),len(X_test),len(y_train),len(y_test))

637644 33561 637644 33561


In [34]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))

c:\program files\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

           0       0.83      0.77      0.80     16454
           1       0.79      0.85      0.82     17107

   micro avg       0.81      0.81      0.81     33561
   macro avg       0.81      0.81      0.81     33561
weighted avg       0.81      0.81      0.81     33561

[[12646  3808]
 [ 2510 14597]]


### On Weekly

In [36]:
y = loan['repayment_interval_weekly']

# 'repayment_interval_bullet', 'repayment_interval_irregular', 'repayment_interval_monthly', 'repayment_interval_weekly'
X = loan
del X['repayment_interval_bullet']
del X['repayment_interval_irregular']
del X['repayment_interval_monthly']
del X['repayment_interval_weekly']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=1)

logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))

c:\program files\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

           0       1.00      1.00      1.00     33531
           1       0.00      0.00      0.00        30

   micro avg       1.00      1.00      1.00     33561
   macro avg       0.50      0.50      0.50     33561
weighted avg       1.00      1.00      1.00     33561

[[33531     0]
 [   30     0]]


c:\program files\python37\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


**Special conclusion on weekly: it sucks as it just all predicted as Not Weekly.  This is not even guessing.**

### On Irregular

In [38]:
y = loan['repayment_interval_irregular']

# 'repayment_interval_bullet', 'repayment_interval_irregular', 'repayment_interval_monthly', 'repayment_interval_weekly'
X = loan
del X['repayment_interval_bullet']
del X['repayment_interval_irregular']
del X['repayment_interval_monthly']
del X['repayment_interval_weekly']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=1)

logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)
predictions = logmodel.predict(X_test)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))

c:\program files\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

           0       0.86      0.92      0.89     20602
           1       0.86      0.77      0.81     12959

   micro avg       0.86      0.86      0.86     33561
   macro avg       0.86      0.84      0.85     33561
weighted avg       0.86      0.86      0.86     33561

[[18915  1687]
 [ 2967  9992]]


## Summary

The model is not doing very well.  But the overall prediction, except `repayment_interval_bullet`, is doing well.  A LDA transformation of data can be used for more performance.  

# Feature Extraction via LDA

In [6]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA

## Logistic Regression

### On Bullet

In [41]:
y = loan['repayment_interval_bullet']

# 'repayment_interval_bullet', 'repayment_interval_irregular', 'repayment_interval_monthly', 'repayment_interval_weekly'
X = loan
del X['repayment_interval_bullet']
del X['repayment_interval_irregular']
del X['repayment_interval_monthly']
del X['repayment_interval_weekly']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=1)

In [42]:
lda = LDA(n_components=2)
X_train_lda = lda.fit_transform(X_train, y_train)
X_test_lda = lda.transform(X_test)

c:\program files\python37\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [43]:
logmodel = LogisticRegression()
logmodel.fit(X_train_lda,y_train)
predictions = logmodel.predict(X_test_lda)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))

c:\program files\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

           0       0.96      0.97      0.97     30096
           1       0.73      0.62      0.67      3465

   micro avg       0.94      0.94      0.94     33561
   macro avg       0.85      0.80      0.82     33561
weighted avg       0.93      0.94      0.94     33561

[[29319   777]
 [ 1310  2155]]


### On Monthly

In [55]:
y = loan['repayment_interval_monthly']

# 'repayment_interval_bullet', 'repayment_interval_irregular', 'repayment_interval_monthly', 'repayment_interval_weekly'
X = loan
del X['repayment_interval_bullet']
del X['repayment_interval_irregular']
del X['repayment_interval_monthly']
del X['repayment_interval_weekly']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=1)

In [56]:
lda = LDA(n_components=2)
X_train_lda = lda.fit_transform(X_train, y_train)
X_test_lda = lda.transform(X_test)

c:\program files\python37\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [57]:
logmodel = LogisticRegression()
logmodel.fit(X_train_lda,y_train)
predictions = logmodel.predict(X_test_lda)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))

c:\program files\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

           0       0.83      0.77      0.80     16454
           1       0.79      0.85      0.82     17107

   micro avg       0.81      0.81      0.81     33561
   macro avg       0.81      0.81      0.81     33561
weighted avg       0.81      0.81      0.81     33561

[[12624  3830]
 [ 2586 14521]]


**It is weird that the performance even get worser.**

### On Weekly

In [59]:
y = loan['repayment_interval_weekly']

# 'repayment_interval_bullet', 'repayment_interval_irregular', 'repayment_interval_monthly', 'repayment_interval_weekly'
X = loan
del X['repayment_interval_bullet']
del X['repayment_interval_irregular']
del X['repayment_interval_monthly']
del X['repayment_interval_weekly']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=1)

In [60]:
lda = LDA(n_components=2)
X_train_lda = lda.fit_transform(X_train, y_train)
X_test_lda = lda.transform(X_test)

c:\program files\python37\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [61]:
logmodel = LogisticRegression()
logmodel.fit(X_train_lda,y_train)
predictions = logmodel.predict(X_test_lda)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))

c:\program files\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

           0       1.00      1.00      1.00     33531
           1       0.00      0.00      0.00        30

   micro avg       1.00      1.00      1.00     33561
   macro avg       0.50      0.50      0.50     33561
weighted avg       1.00      1.00      1.00     33561

[[33531     0]
 [   30     0]]


c:\program files\python37\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


### On Irregular

In [71]:
y = loan['repayment_interval_irregular']

# 'repayment_interval_bullet', 'repayment_interval_irregular', 'repayment_interval_monthly', 'repayment_interval_weekly'
X = loan
del X['repayment_interval_bullet']
del X['repayment_interval_irregular']
del X['repayment_interval_monthly']
del X['repayment_interval_weekly']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=1)

In [72]:
lda = LDA(n_components=10)
X_train_lda = lda.fit_transform(X_train, y_train)
X_test_lda = lda.transform(X_test)

c:\program files\python37\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [73]:
logmodel = LogisticRegression()
logmodel.fit(X_train_lda,y_train)
predictions = logmodel.predict(X_test_lda)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))

c:\program files\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


              precision    recall  f1-score   support

           0       0.85      0.93      0.89     20602
           1       0.86      0.74      0.80     12959

   micro avg       0.86      0.86      0.86     33561
   macro avg       0.86      0.84      0.84     33561
weighted avg       0.86      0.86      0.85     33561

[[19096  1506]
 [ 3323  9636]]


# SVM

In [7]:
from sklearn import svm

## On Bullet

In [8]:
y = loan['repayment_interval_bullet']

# 'repayment_interval_bullet', 'repayment_interval_irregular', 'repayment_interval_monthly', 'repayment_interval_weekly'
X = loan
del X['repayment_interval_bullet']
del X['repayment_interval_irregular']
del X['repayment_interval_monthly']
del X['repayment_interval_weekly']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=1)

In [17]:
lda = LDA(n_components=2)
X_train_lda = lda.fit_transform(X_train, y_train)
X_test_lda = lda.transform(X_test)

c:\program files\python37\lib\site-packages\sklearn\discriminant_analysis.py:388: UserWarning: Variables are collinear.
  warnings.warn("Variables are collinear.")


In [ ]:
clf = svm.SVC(gamma='scale')
clf.fit(X_train_lda, y_train)
predictions = clf.predict(X_test_lda)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))

# Decision Tree

In [18]:
from sklearn import tree

## On Bullet

In [16]:
y = loan['repayment_interval_bullet']

# 'repayment_interval_bullet', 'repayment_interval_irregular', 'repayment_interval_monthly', 'repayment_interval_weekly'
X = loan
del X['repayment_interval_bullet']
del X['repayment_interval_irregular']
del X['repayment_interval_monthly']
del X['repayment_interval_weekly']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.05, random_state=1)

array([5.21117201])

In [20]:
dtree = tree.DecisionTreeClassifier()
dtree.fit(X_train_lda, y_train)
y_test = dtree.predict(X_test_lda)
print(classification_report(y_test,predictions))
print(confusion_matrix(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     30107
           1       1.00      1.00      1.00      3454

   micro avg       1.00      1.00      1.00     33561
   macro avg       1.00      1.00      1.00     33561
weighted avg       1.00      1.00      1.00     33561

[[30107     0]
 [    0  3454]]


### Random Forest

In [ ]:
forest = RandomForestClassifier(n_estimators=100, max_depth=4)
forest.fit(X_train_lda, y_train)
